module.exports = {
	name: "50 State Benefits", // optional, falls back to object key
	description: "50 State Benefits",
	options: {
		runs: 1,
		frequency: 60 * 12, // (in minutes)
		freshChrome: "run",
	},
	urls: [
    "https://www.connect.ct.gov/",
    "https://assist.dhss.delaware.gov/",
    "https://maine.gov/benefits/account/login.html",
    "https://nheasy.nh.gov/",
    "https://mydhrbenefits.dhr.state.md.us/",
    "https://www.marylandhealthconnection.gov/",
    // "https://dtaconnect.eohhs.mass.gov/",
    // "https://www.mahealthconnector.org/",
    // "https://www.mass.gov/forms/apply-for-wic-online",
    // "https://oneapp.dhs.state.nj.us/",
    // "http://www.njfamilycare.org/",
    // "https://www.mybenefits.ny.gov/",
    // "https://a069-access.nyc.gov/accesshra/",
    // "https://www.compass.state.pa.us/compass.web/Public/CMPHome",
    // "https://www.pawic.com/OnlineApplication.aspx",
    // "https://healthyrhode.ri.gov/HIXWebI3/DisplayHomePage",
    // "http://dcf.vermont.gov/mybenefits/apply",
    // "https://portal.healthconnect.vermont.gov",
		"https://aries.alaska.gov/screener/?logIn=N",
		"https://www.mybenefitscalwin.org/",
		"https://www.c4yourself.com/",
		"https://www.yourbenefits.laclrs.org/",
		"https://www.healthearizonaplus.gov/Default/Default.aspx",
		"https://coloradopeak.secure.force.com/",
		// "https://www.healthinformatics.dphe.state.co.us/WICSignUp",
		// "http://humanservices.hawaii.gov/",
		// "http://healthandwelfare.idaho.gov/FoodCashAssistance/ApplyforAssistance/tabid/1554/Default.aspx",
		// "https://apply.mt.gov/access/accessController?id=0.488303387473776",
		// "https://dwss.nv.gov/Apply/APPLY/",
		// "https://www.yes.state.nm.us/",
		// "https://apps.state.or.us/onlineApplication",
		// "https://healthcare.oregon.gov/Pages/index.aspx",
		// "https://jobs.utah.gov/mycase/",
		// "https://www.wahealthplanfinder.org/",
		// "https://www.washingtonconnection.org/home/",
		// "https://www.wesystem.wyo.gov/AVANCE_ONLINE_APP/Landing.action",
		// "https://www.wyolieap.com/Application/",
		"https://alabamacares.alabama.gov",
    "https://mydhr.alabama.gov/",
    "https://eligibilityenrollment.arkansas.gov/CitizenPortal/application.do",
    "https://gateway.ga.gov/access/",
    "https://gaprereg.statewic.net/",
    "https://dcf-access.dcf.state.fl.us/access/scrflstartappl.do?performAction=init&showMensaje=true",
    // "https://www.benefind.ky.gov",
    // "https://cafe-cp.dcfs.la.gov/selfservice/",
    // "https://sspweb.lameds.ldh.la.gov/selfservice/selfserviceController?id=0.9440837580604988&tab=1",
    // "https://www.access.ms.gov/",
    // "https://www.epass.nc.gov/CitizenPortal/application.do",
    // "https://www.okdhslive.org/",
    // "https://scmapp.sc.gov/Default.aspx",
    // "https://apply.scdhhs.gov/CitizenPortal/application.do",
    // "https://tenncareconnect.tn.gov/services/HomePage",
    // "http://tn.gov/humanserv/forms/FAApp.shtml",
    // "https://www.yourtexasbenefits.com/ssp/SSPHome/ssphome.jsp",
    // "https://texaswic.az1.qualtrics.com/jfe/form/SV_6G3nsSAEyVNzixn?Q_Language=EN",
    // "https://www.myvawic.org/",
    // "https://commonhelp.virginia.gov/access/accessController?id=0.9048415000315394",
    // "https://wvwichousehold.wvdhhr.org/",
    // "https://www.wvinroads.org/selfservice/",
		"https://abe.illinois.gov/abe/access/",
    "https://fssabenefits.in.gov/bp/#/",
    "https://secureapp.dhs.state.ia.us/oasis/OASIS0100.aspx",
    "https://dhsservices.iowa.gov/apspssp/ssp.portal",
    "http://www.dcf.ks.gov/services/ees/Pages/Application-for-benefits.aspx",
    "https://newmibridges.michigan.gov/s/isd-landing-page?language=en_US",
    // "https://applymn.dhs.mn.gov/online-app-web/spring/public/process-login?execution=e1s1",
    // "https://auth.mnsure.org/RIDP/?account_type=Individual",
    // "https://mydss.mo.gov/",
    // "http://www.nd.gov/dhs/eligibility/index.html",
    // "http://dhhs.ne.gov/Children_Family_Services/AccessNebraska/Pages/accessnebraska_index.aspx",
    // "https://odjfsbenefits.ohio.gov/SelfServiceSplash.jsf",
    // "https://apps.sd.gov/ss36snap/web/Portal/Default.aspx",
    // "https://access.wisconsin.gov/access/",
	]
};
